# Generated by Django 4.0.6 on 2023-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('money', models.IntegerField(auto_created=True, default=0)),
                ('inviter_id', models.IntegerField(auto_created=True, default=0, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('invited_users', models.TextField(null=True)),
            ],
        ),
    ]
