# Generated by Django 4.0.6 on 2023-02-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_user_money_alter_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_sub',
            field=models.BooleanField(default=False),
        ),
    ]
